// Build step: render the Keel repo's markdown docs to HTML and bake them into
// the Worker as src/docs/generated.ts. One source of truth — the guides live in
// the keel repo (docs/*.md); this site renders them verbatim. Reads the sibling
// checkout (docs aren't shipped in the npm package, which is `files: ["dist"]`).
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { Marked } from "marked";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// Prefer the installed package's docs; fall back to the sibling checkout.
const candidates = [join(root, "node_modules/keel/docs"), join(root, "../keel/docs")];
const docsDir = candidates.find((d) => existsSync(d));
if (!docsDir) {
  console.error("build-docs: no docs directory found in", candidates);
  process.exit(1);
}

// Conceptual pages have no exported API and use these slugs; everything else is
// an API guide. The ordering here drives the sidebar sections.
const SECTIONS = [
  { title: "Getting Started", slugs: ["getting-started"] },
  {
    title: "The Basics",
    slugs: ["container", "providers", "configuration", "routing", "controllers", "request-response", "decorators", "middleware", "hooks", "views", "templates", "vite", "errors"],
  },
  {
    title: "Database",
    slugs: ["database", "models", "migrations", "factories", "transformers"],
  },
  {
    title: "Auth & Security",
    slugs: ["sessions", "authentication", "hashing", "rate-limiting"],
  },
  {
    title: "Digging Deeper",
    slugs: ["mail", "queues", "notifications", "events", "cache", "redis", "logger", "validation", "url-builder", "static-files", "inertia", "helpers", "debugging", "testing", "console"],
  },
  { title: "Under the Hood", slugs: ["hono", "architecture"] },
];

function slugForHeading(text) {
  return text
    .toLowerCase()
    .replace(/`/g, "")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

// A Marked instance that rewrites cross-doc links (foo.md -> /docs/foo) and adds
// id anchors to headings so in-page `#section` links work.
function makeMarked() {
  const marked = new Marked({ gfm: true });
  const renderer = {
    heading({ tokens, depth }) {
      const text = this.parser.parseInline(tokens);
      const id = slugForHeading(this.parser.parseInline(tokens).replace(/<[^>]+>/g, ""));
      return `<h${depth} id="${id}">${text}</h${depth}>\n`;
    },
    link({ href, title, tokens }) {
      const text = this.parser.parseInline(tokens);
      let h = href;
      // ./models.md#relationships -> /docs/models#relationships ; foo.md -> /docs/foo
      const m = /^\.?\/?([\w-]+)\.md(#.*)?$/.exec(href);
      if (m) h = `/docs/${m[1]}${m[2] ?? ""}`;
      const t = title ? ` title="${title}"` : "";
      const ext = /^https?:/.test(h) ? ' target="_blank" rel="noopener"' : "";
      return `<a href="${h}"${t}${ext}>${text}</a>`;
    },
  };
  marked.use({ renderer });
  return marked;
}

const marked = makeMarked();
const known = new Set(readdirSync(docsDir).filter((f) => f.endsWith(".md")).map((f) => f.replace(/\.md$/, "")));

const pages = {};
for (const section of SECTIONS) {
  for (const slug of section.slugs) {
    if (!known.has(slug)) {
      console.error(`build-docs: SECTIONS references "${slug}" but ${slug}.md is missing`);
      process.exit(1);
    }
    const md = readFileSync(join(docsDir, `${slug}.md`), "utf8");
    const titleMatch = /^#\s+(.+)$/m.exec(md);
    const title = titleMatch ? titleMatch[1].trim() : slug;
    // Drop the leading H1 (the page renders its own title) and render the rest.
    const body = md.replace(/^#\s+.+$\n?/m, "");
    const html = marked.parse(body);
    pages[slug] = { title, html };
  }
}

// Warn about any guide not placed in a section (so nothing silently drops).
const placed = new Set(SECTIONS.flatMap((s) => s.slugs));
for (const slug of known) {
  if (!placed.has(slug)) console.warn(`build-docs: ${slug}.md is not in any section (skipped)`);
}

const groups = SECTIONS.map((s) => ({ title: s.title, pages: s.slugs }));
const order = SECTIONS.flatMap((s) => s.slugs);

const out = `// GENERATED by scripts/build-docs.mjs from the keel repo's docs/*.md — do not edit.
export interface DocPage { title: string; html: string; }
export const PAGES: Record<string, DocPage> = ${JSON.stringify(pages)};
export const GROUPS: { title: string; pages: string[] }[] = ${JSON.stringify(groups)};
export const ORDER: string[] = ${JSON.stringify(order)};
`;

writeFileSync(join(root, "src/docs/generated.ts"), out);
console.log(`build-docs: rendered ${Object.keys(pages).length} guides from ${docsDir}`);
